server:
  port: 10100
spring:
  application:
    name: service-pay #服务名
  datasource:
    url: jdbc:mysql:///ymcc-pay?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
    discovery:
    server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
rocketmq:
  name-server: 127.0.0.1:9876
  # 是否开启自动配置
  producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    group: "service-pay-producer"
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    # 发送消息超时时间，默认 3000
    send-message-timeout: 3000
    # 发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
mybatis-plus:
  mapper-locations: classpath:cn/zwh/ymcc/mapper/*Mapper.xml
  configuration: #mybatis-plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
